services:
  web:
    build:
      target: dev
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - webpack-cache:/app/webpack-cache
    stdin_open: true
    tty: true

volumes:
  node_modules:
  webpack-cache: